// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGmrXYvX_iygYoA6A10D4KpIJOURFhxBE',
    appId: '1:407629543154:web:3645e380ce9e056d88026b',
    messagingSenderId: '407629543154',
    projectId: 'vocal-lens',
    authDomain: 'vocal-lens.firebaseapp.com',
    storageBucket: 'vocal-lens.firebasestorage.app',
    measurementId: 'G-FLMN2DTL7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfeDoGD4uDJMNcQrAKMTHFIyyG2VH3_-c',
    appId: '1:407629543154:android:b8406e103d52642388026b',
    messagingSenderId: '407629543154',
    projectId: 'vocal-lens',
    storageBucket: 'vocal-lens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs5Kx8To8kdM5OnWuGeu5Z-Z7aO2F2_HE',
    appId: '1:407629543154:ios:719cc5a36a60342688026b',
    messagingSenderId: '407629543154',
    projectId: 'vocal-lens',
    storageBucket: 'vocal-lens.firebasestorage.app',
    iosBundleId: 'com.example.vocalLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs5Kx8To8kdM5OnWuGeu5Z-Z7aO2F2_HE',
    appId: '1:407629543154:ios:719cc5a36a60342688026b',
    messagingSenderId: '407629543154',
    projectId: 'vocal-lens',
    storageBucket: 'vocal-lens.firebasestorage.app',
    iosBundleId: 'com.example.vocalLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGmrXYvX_iygYoA6A10D4KpIJOURFhxBE',
    appId: '1:407629543154:web:ab84bbd607cf930488026b',
    messagingSenderId: '407629543154',
    projectId: 'vocal-lens',
    authDomain: 'vocal-lens.firebaseapp.com',
    storageBucket: 'vocal-lens.firebasestorage.app',
    measurementId: 'G-H04NQPM15G',
  );
}
